In [1]:
import pandas as pd

In [2]:
pricing = pd.read_excel(
     r"C:\Users\nasee\Downloads\KaziConnect_Week_6_Business_Model_and_Pricing_Pack.xlsx",
    sheet_name="User Pricing"
)

pricing_filtered = pricing[
    (pricing["current_status"] == "Recent graduate")
    &
    (pricing["preferred_solution"] == "Application status tracker")
]

pricing_filtered

,user_id,current_status,preferred_solution,tested_price_ugx,willingness_to_pay,preferred_payment_model,preferred_payer,ability_to_pay_concern,free_core_required,interest_1_5,trust_concern,data_cost_concern,open_comment
0,KC-0001,Recent graduate,Application status tracker,5000,Yes,Low monthly subscription,Self,No,No,5,No,No,"I could pay UGX 5,000 if application status tr..."
1,KC-0003,Recent graduate,Application status tracker,15000,Maybe,Free core plus paid add-on,University or NGO,Yes,Yes,4,No,No,"I may pay after trying the service, but the ba..."
4,KC-0009,Recent graduate,Application status tracker,5000,Maybe,Low monthly subscription,Self,Yes,Yes,4,No,No,"I may pay after trying the service, but the ba..."
9,KC-0033,Recent graduate,Application status tracker,20000,Maybe,One-off fee,Self,Yes,Yes,5,No,No,"I may pay after trying the service, but the ba..."
13,KC-0047,Recent graduate,Application status tracker,20000,Yes,Employer-sponsored access,University or NGO,Yes,Yes,5,No,No,"I could pay UGX 20,000 if application status t..."
16,KC-0053,Recent graduate,Application status tracker,15000,Maybe,One-off fee,Self,Yes,Yes,3,No,Yes,"I may pay after trying the service, but the ba..."
19,KC-0059,Recent graduate,Application status tracker,15000,Yes,One-off fee,Self,Yes,Yes,4,No,No,"I could pay UGX 15,000 if application status t..."
20,KC-0061,Recent graduate,Application status tracker,10000,Maybe,Employer-sponsored access,University or NGO,No,No,4,No,Yes,"I may pay after trying the service, but the ba..."
22,KC-0071,Recent graduate,Application status tracker,20000,Maybe,Institution-sponsored access,Shared payment,Yes,Yes,5,No,Yes,"I may pay after trying the service, but the ba..."
25,KC-0093,Recent graduate,Application status tracker,5000,Maybe,Employer-sponsored access,Shared payment,No,Yes,5,No,No,"I may pay after trying the service, but the ba..."
32,KC-0123,Recent graduate,Application status tracker,15000,Maybe,Employer-sponsored access,University or NGO,Yes,Yes,4,Yes,No,"I may pay after trying the service, but the ba..."
33,KC-0125,Recent graduate,Application status tracker,15000,Yes,Low monthly subscription,Self,Yes,Yes,4,No,No,"I could pay UGX 15,000 if application status t..."
37,KC-0139,Recent graduate,Application status tracker,15000,Yes,Institution-sponsored access,Employer,Yes,Yes,4,No,No,"I could pay UGX 15,000 if application status t..."
42,KC-0163,Recent graduate,Application status tracker,20000,Yes,Low monthly subscription,Self,Yes,Yes,5,No,No,"I could pay UGX 20,000 if application status t..."
44,KC-0167,Recent graduate,Application status tracker,5000,Yes,Employer-sponsored access,University or NGO,No,No,4,Yes,Yes,"I could pay UGX 5,000 if application status tr..."

In [3]:
len(pricing_filtered)

15

In [4]:
pricing_filtered["willingness_to_pay"].value_counts()

willingness_to_pay
Maybe    8
Yes      7
Name: count, dtype: int64

In [5]:
pricing_filtered["preferred_payer"].value_counts()

preferred_payer
Self                 7
University or NGO    5
Shared payment       2
Employer             1
Name: count, dtype: int64

In [6]:
pricing_filtered["preferred_payment_model"].value_counts()

preferred_payment_model
Employer-sponsored access       5
Low monthly subscription        4
One-off fee                     3
Institution-sponsored access    2
Free core plus paid add-on      1
Name: count, dtype: int64

In [7]:
pricing_filtered["ability_to_pay_concern"].value_counts()

ability_to_pay_concern
Yes    11
No      4
Name: count, dtype: int64

In [8]:
pricing_filtered["free_core_required"].value_counts()

free_core_required
Yes    12
No      3
Name: count, dtype: int64

In [9]:
pricing_filtered["tested_price_ugx"].describe()

count       15.000000
mean     13333.333333
std       5875.696514
min       5000.000000
25%       7500.000000
50%      15000.000000
75%      17500.000000
max      20000.000000
Name: tested_price_ugx, dtype: float64

In [10]:
employers = pd.read_excel(
     r"C:\Users\nasee\Downloads\KaziConnect_Week_6_Business_Model_and_Pricing_Pack.xlsx",
    sheet_name="Employer Evidence"
)

application_tracking = employers[
    employers["offer_tested"] == "Application tracking"
]

application_tracking

,employer_id,organisation_size,sector,hires_last_12_months,main_recruitment_pain,paid_recruitment_before,preferred_payment_model,offer_tested,tested_price_ugx,purchase_intent,interest_1_5,max_budget_for_model_ugx,decision_role,main_concern,open_comment
6,EMP-007,Medium 21-100,Health,6,Slow screening,Yes,Success fee per hire,Application tracking,180000,Yes,5,285000,Owner,Would require manager approval,I would consider success fee per hire if appli...
13,EMP-014,Small 6-20,Technology,5,Slow screening,Yes,Employer subscription,Application tracking,150000,Maybe,3,185000,HR manager,Need proof of candidate quality,"The offer is relevant, but I need evidence tha..."
23,EMP-024,Large 101+,Hospitality,18,Slow screening,Yes,Pay per job posting,Application tracking,30000,Yes,5,805000,Administrator,Would require manager approval,I would consider pay per job posting if applic...
25,EMP-026,Small 6-20,Logistics,5,Slow screening,No,Success fee per hire,Application tracking,180000,No,4,120000,HR manager,Would require manager approval,I would not commit at this price until KaziCon...
26,EMP-027,Medium 21-100,Professional services,12,Limited recruitment data,No,Employer subscription,Application tracking,150000,Yes,4,290000,Operations manager,Would require manager approval,I would consider employer subscription if appl...
43,EMP-044,Large 101+,Education,17,Limited recruitment data,Yes,Employer subscription,Application tracking,250000,Yes,5,540000,HR manager,Need a clear service level,I would consider employer subscription if appl...

In [11]:
len(application_tracking)

6

In [12]:
application_tracking["purchase_intent"].value_counts()

purchase_intent
Yes      4
Maybe    1
No       1
Name: count, dtype: int64

In [13]:
application_tracking["preferred_payment_model"].value_counts()

preferred_payment_model
Employer subscription    3
Success fee per hire     2
Pay per job posting      1
Name: count, dtype: int64

In [14]:
application_tracking["tested_price_ugx"].describe()

count         6.000000
mean     156666.666667
std       72018.516138
min       30000.000000
25%      150000.000000
50%      165000.000000
75%      180000.000000
max      250000.000000
Name: tested_price_ugx, dtype: float64

In [15]:
application_tracking["max_budget_for_model_ugx"].describe()

count         6.000000
mean     370833.333333
std      256308.733107
min      120000.000000
25%      210000.000000
50%      287500.000000
75%      477500.000000
max      805000.000000
Name: max_budget_for_model_ugx, dtype: float64

In [16]:
application_tracking[
    [
        "purchase_intent",
        "tested_price_ugx",
        "max_budget_for_model_ugx"
    ]
]

   purchase_intent  tested_price_ugx  max_budget_for_model_ugx
6              Yes            180000                    285000
13           Maybe            150000                    185000
23             Yes             30000                    805000
25              No            180000                    120000
26             Yes            150000                    290000
43             Yes            250000                    540000

In [17]:
application_tracking["open_comment"]

6     I would consider success fee per hire if appli...
13    The offer is relevant, but I need evidence tha...
23    I would consider pay per job posting if applic...
25    I would not commit at this price until KaziCon...
26    I would consider employer subscription if appl...
43    I would consider employer subscription if appl...
Name: open_comment, dtype: str